Added If else
added if else since
In Android on 2020-02-04 at 14:37:14 - Error compiling Cordova plugin: main/java/com/stratpoint/cordova/plugin/CustomJumio.java:311: error: unreachable statement.