object to string to object approach
change 			
JSONObject optionsproper = options.getJSONObject("options");	
to 
JSONObject optionsproper = new JSONObject(options.getString("options"));

because 
In Android on 2020-02-12 at 19:42:17 - Error compiling Cordova plugin: main/java/com/stratpoint/cordova/plugin/CustomJumio.java:329: error: cannot find symbol.