modified parsing
from 			JSONObject optionsproper = options1.getString("options");	
to                       JSONParser parser = new JSONParser();
			JSONObject optionsproper = (JSONObject) parser.parse(options1.getString("options"););

because 
/tmp/build/source/platforms/android/app/src/main/java/com/stratpoint/cordova/plugin/CustomJumio.java:329: error: incompatible types: String cannot be converted to JSONObject:	JSONObject optionsproper = options1.getString("options");