added a number 1 in the variable
from 			JSONObject optionsproper = new JSONObject(options.getString("options"));	
to 			JSONObject optionsproper = new JSONObject(options1.getString("options"));
because

 In Android on 2020-02-12 at 19:49:02 - Error compiling Cordova plugin: main/java/com/stratpoint/cordova/plugin/CustomJumio.java:329: error: cannot find symbol.

ugh