Update CustomJumio.java
from				showErrorMessage(myoptions);	
to				showErrorMessage(myoptions.getString("customerId"));


because
In Android on 2020-02-13 at 10:33:22 - Error compiling Cordova plugin: main/java/com/stratpoint/cordova/plugin/CustomJumio.java:344: error: incompatible types: JSONObject cannot be converted to String.